ornito_observation_homepage:
    path: /{page}
    defaults:
        _controller: OrnitoObservationBundle:Observation:index
        page: 1
    requirements:
        page: \d+

ornito_observation_add:
    path: /add
    defaults:
        _controller: OrnitoObservationBundle:Observation:add

ornito_observation_view:
    path: /view/{id}
    defaults:
        _controller: OrnitoObservationBundle:Observation:view
    requirements:
        id: \d+

ornito_observation_edit:
    path: /edit/{id}
    defaults:
        _controller: OrnitoObservationBundle:Observation:edit
    requirements:
        id: \d+

ornito_observation_delete:
    path: /delete/{id}
    defaults:
        _controller: OrnitoObservationBundle:Observation:delete
    requirements:
        id: \d+

ornito_observation_waiting:
    path: /waiting/{page}
    defaults:
        _controller: OrnitoObservationBundle:Observation:waiting
        page: 1
    requirements:
        page: \d+

ornito_observation_validate:
    path: /validate/{id}
    defaults:
        _controller: OrnitoObservationBundle:Observation:validate
    requirements:
        id: \d+

