<?php

namespace Ornito\ObservationBundle\Repository;

/**
 * WatchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchingRepository extends \Doctrine\ORM\EntityRepository
{
}
