ornito_research:
    resource: "@OrnitoResearchBundle/Resources/config/routing.yml"
    prefix:   /research

ornito_observation:
    resource: "@OrnitoObservationBundle/Resources/config/routing.yml"
    prefix:   /observation

ornito_core:
    resource: "@OrnitoCoreBundle/Resources/config/routing.yml"
    prefix:   /


