ornito_user:
    resource: "@OrnitoUserBundle/Resources/config/routing.yml"
    prefix:   /

ornito_inventory:
    resource: "@OrnitoTaxrefBundle/Resources/config/routing.yml"
    prefix:   /inventory

ornito_observation:
    resource: "@OrnitoObservationBundle/Resources/config/routing.yml"
    prefix:   /observation

ornito_main:
    resource: "@OrnitoMainBundle/Resources/config/routing.yml"
