ornito_map:
    resource: "@OrnitoMapBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/map
    requirements:
        _locale: %app.locales%

ornito_inventory:
    resource: "@OrnitoTaxrefBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/inventory
    requirements:
        _locale: %app.locales%

ornito_observation:
    resource: "@OrnitoObservationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/observation
    requirements:
        _locale: %app.locales%

ornito_main:
    resource: "@OrnitoMainBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %app.locales%

ornito_user:
    resource: "@OrnitoUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %app.locales%

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
