ornito_observation:
    resource: "@OrnitoObservationBundle/Resources/config/routing.yml"
    prefix:   /observation

ornito_core:
    resource: "@OrnitoCoreBundle/Resources/config/routing.yml"
    prefix:   /


