<?php

namespace Ornito\ResearchBundle\Repository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
}
