ornito_map_homepage:
    path:     /
    defaults:
        _controller: OrnitoMapBundle:Map:index

ornito_map_search:
    path:     /search/{name}/{value}
    defaults:
        _controller: OrnitoMapBundle:Map:search
        name:
        value: