<?php

namespace Ornito\TaxrefBundle\Repository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get a list of a column with its name given in parameter
     * @return array by alphabetical order
     */
    public function getList($columnName)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s.'.$columnName)
            ->distinct(true)
        ;
        $result = $qb
            ->getQuery()
            ->getArrayResult()
        ;
        sort($result);
        return $result;
    }

    /**
     * Get a list of species
     * Parameters are the column's name & the value we want to find
     * @return array
     */
    public function mySelectList($columnName, $value)
    {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->where('s.' . $columnName . ' = :' . $columnName)
            ->setParameter($columnName, $value)
            ->orderBy('s.scientificName')
        ;
        return $qb
            ->getQuery()
            ->getArrayResult()
        ;
    }

    /**
     * Get the list of species
     * @return array
     */
    public function findAllSpecies()
    {
        $queryBuilder = $this->createQueryBuilder('species');
        $query = $queryBuilder->getQuery();
        $results = $query->getScalarResult();
        return $results;
    }


    /**
     * Get the list of species by scientific name alphabetical order
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getScientificNameByAlpha()
    {
        return $this
            ->createQueryBuilder('s')
            ->orderBy('s.scientificName', 'ASC')
            ;
    }
}
