<?php

namespace Ornito\TaxrefBundle\Repository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get a list of a column with its name given in parameter
     * @return array by alphabetical order
     */
    public function getList($columnName)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s.'.$columnName)
            ->distinct(true)
        ;
        $result = $qb
            ->getQuery()
            ->getArrayResult();
        sort($result);
        return $result;
    }

    /**
     * Get the list of species
     * @return array
     */
    public function mySelectList()
    {
        $queryBuilder = $this->createQueryBuilder('species');
        $query = $queryBuilder->getQuery();
        $results = $query->getScalarResult();
        return $results;
    }
}
